Global Header: Add in styles to fix older browsers.
WordPress/wporg-mu-plugins pull request #178
Opened 2022-03-07 05:48 UTC by StevenDufresne

This PR copies in Gutenberg Navigation styles that include the `:where` CSS declaration which causes unusable layouts in [older browsers](https://caniuse.com/?search=where).

Fixes #159

## Why does Gutenberg use `:where`?
Gutenberg uses these conditional css selectors because the Navigation component has a "Open on click" feature:

<img src="https://d.pr/i/G2msiQ.png" width="200px">

When that feature is toggled on, the `hover` functionality is not added to the submenus.

## What are the risks?
There isn't much risk since the CSS is implemented behind the `supports` declaration,  however:
- Should we ever turn on "Open on Click" for the menu, these changes will not work for that. 
- Technical CSS debt in an "active" CSS file.

## Screenshots
_Environment: Windows 8.1 - Chrome 69_  
| Before | After |
| --- | --- |
| <img src="https://d.pr/i/1pZsrH.png" width="400px"> | <img src="https://d.pr/i/tmGofy.png" width="400px"> |

## Incidental Changes
In order to use `@supports`, we need to update `postcss-preset-env`.  The current version is using an older `autoprefixr` version that does not support `@supports`.

2022-03-07 15:52 UTC, ryelle requested changes
Visually this looks good (tested on Chrome 87), but the dropdowns can't be accessed by keyboard anymore. I _think_ you can use `:focus-within` on the same element as `:hover`, but maybe double check the browser support.

2022-03-07 22:44 UTC, StevenDufresne commented
> Visually this looks good (tested on Chrome 87), but the dropdowns can't be accessed by keyboard anymore. I _think_ you can use `:focus-within` on the same element as `:hover`, but maybe double check the browser support.

Thanks for catching that! I'll take a look.

2022-03-08 00:53 UTC, StevenDufresne commented
Ok, using `focus-within` seems to work with chrome. 👍  

I tested all the way back to Chrome 68. However, Falkon in my Virtual Machine won't tab into the navigation at all, which is a bit bizarre. It should work... 🤔

If we are okay with these changes, we could merge this PR, and reopen a new ticket with a smaller scope if that is still in fact a problem. It will give people a better ability to test these changes with little risk.

2022-03-08 18:01 UTC, ryelle approved these changes
Working with keyboard nav & screen reader (VO). 

I left one comment that would be an improvement, but it's not a blocker since that's also how it works on production.

2022-03-08 18:01 UTC, ryelle commented on mu-plugins/blocks/global-header-footer/postcss/header/menu.pcss
> +			visibility: hidden;
Is this rule necessary? Technically it removes the element from the accessibility tree, so it no longer shows up in VoiceOver's links menu. The links are still accessible on the page, it's just the menu in the rotor that's missing it.

2022-03-10 06:20 UTC, StevenDufresne commented
@ryelle Since #159 doesn't support selector support checks, any reservations just including the CSS for all browsers? I can't think of a good way to target CSS 4 selectors.

2022-03-10 15:58 UTC, ryelle commented
> any reservations just including the CSS for all browsers?

The risks you identified would now apply to all browsers, rather than just the older ones. We'll need to maintain the CSS, so if the nav block markup changes, our CSS won't know about that. Honestly that's probably true for other things on the site too, so it's not a blocker.

2022-03-23 01:43 UTC, merged