Add taxonomy to apply button of query filter block
WordPress/wporg-mu-plugins pull request #469
Opened 2023-10-08 19:02 UTC by renintw

Closes https://github.com/WordPress/wporg-showcase-2022/issues/225

This PR adds taxonomy to query-filter block as per discussion the discussion [here](https://github.com/WordPress/wporg-showcase-2022/issues/225#issuecomment-1749041605). 

<img width="322" alt="Screen Shot 2023-10-09 at 3 59 21 AM" src="https://github.com/WordPress/wporg-mu-plugins/assets/18050944/d5b3696f-f752-46be-ae83-5cc4dd8388c7">

2023-10-09 01:36 UTC, adamwoodnz requested changes
Great start, there are a few grammatical issues with this though, regarding singular and plural states 🙂 

### Screenshots

| 2 tags | 1 flavor |
|-|-|
| ![Screenshot 2023-10-09 at 2 27 38 PM](https://github.com/WordPress/wporg-mu-plugins/assets/1017872/40c64e66-6f51-4477-acab-a1c7fdf91827) | ![Screenshot 2023-10-09 at 2 27 02 PM](https://github.com/WordPress/wporg-mu-plugins/assets/1017872/2a0d4130-f6a6-49e3-9aef-8a620d602d98) |

'Apply (2) popular' doesn't make complete sense without 'tag'. I think we could actually drop the brackets to make the language more natural too. Suggest it should read 'Apply 1 popular tag' if singular, and 'Apply 2 popular tags' if plural.

'Apply (1) flavors' should read 'Apply 1 flavor' if singular, and 'Apply 2 flavors' if plural.

@WordPress/meta-design thoughts please?

2023-10-09 01:39 UTC, adamwoodnz commented on mu-plugins/blocks/query-filter/render.php
> +		/* translators: 1: the count of currently selected filters. 2: post taxonomy */
```suggestion
		/* translators: 1: the count of currently selected filters. 2: taxonomy being filtered */
```

2023-10-09 01:40 UTC, adamwoodnz commented on mu-plugins/blocks/query-filter/src/view.js
> +			/* translators: 1: the count of currently selected filters. 2: post taxonomy */
```suggestion
			/* translators: 1: the count of currently selected filters. 2: taxonomy being filtered */
```

2023-10-09 03:47 UTC, renintw commented
> Apply (2) popular' doesn't make complete sense without 'tag'.

👍  Fixed

>  drop the brackets

I don't have a strong preference for the brackets. I've pushed the commit and included a screenshot here for reference.

| popular tags | categories | flavors |
| ------------| ------------| -------|
| <img width="322" alt="image" src="https://github.com/WordPress/wporg-mu-plugins/assets/18050944/1ef1a892-a47d-4cd6-9833-51344baa62c2"> | <img width="321" alt="image" src="https://github.com/WordPress/wporg-mu-plugins/assets/18050944/026f5af5-beac-4bda-a4b5-9601f7158670"> | <img width="322" alt="image" src="https://github.com/WordPress/wporg-mu-plugins/assets/18050944/f813f36e-96d4-403d-a4d2-98a6ae09c5a4"> |

2023-10-09 08:43 UTC, renintw commented
> Suggest it should read 'Apply 1 popular tag' if singular, and 'Apply 2 popular tags' if plural.

👍 Updated in 5d6b80d5ae7e99e537b39cfb44a27fb796132ad2

<img width="321" alt="Screen Shot 2023-10-09 at 5 42 06 PM" src="https://github.com/WordPress/wporg-mu-plugins/assets/18050944/11914683-3046-4dbd-abad-1c0d785d2af0">

2023-10-09 13:25 UTC, renintw commented
Note: Based on the [discussion](https://github.com/WordPress/wporg-showcase-2022/issues/225#issuecomment-1752974049) in the ticket, this PR might not be needed anymore.

2023-10-10 07:31 UTC, jasmussen commented
I'll defer to @ndiego and @StevenDufresne on this one!

2023-10-10 11:16 UTC, renintw commented
Drop GIFs here for better decision-making.
| Before | After |
| ------| -----|
| ![1](https://github.com/WordPress/wporg-mu-plugins/assets/18050944/dfa1eded-315e-4549-8e87-a95bd344eb82) | ![2](https://github.com/WordPress/wporg-mu-plugins/assets/18050944/5992920f-20ed-4349-811a-d7ec5abc3a97) |

2023-10-10 11:20 UTC, ndiego commented
Thanks for all your hard work here @renintw. Let's stick with https://github.com/WordPress/wporg-showcase-2022/pull/228 for now, and pending any additional user feedback, we could add this PR as well. But hopefully, the term counts is enough.

2023-10-10 11:27 UTC, closed without merging